version: "2"
run:
  go: "1.25"
  tests: true
linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - noctx
    - prealloc
    - revive
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - staticcheck
    - unconvert
    - unused
  settings:
    funlen:
      lines: 100
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    govet:
      enable:
        - shadow
    revive:
      rules:
        - name: exported
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
          - funlen
          - goconst
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
